version: '3.8'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    container_name: db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    # Качаем с Docker Hub:
    image: mikhailfil/taski_backend
    container_name: backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    image: mikhailfil/taski_frontend
    container_name: frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: mikhailfil/taski_gateway
    container_name: gateway
    volumes:
      - static_volume:/staticfiles
    ports:
      - 8000:80
    depends_on:
      - backend